### ISSUE TITLE
Integration Fabric - Firebase

### ISSUE THREAD

**Issue by thpoiani** [sarriaroman/FabricPlugin#121]
Hello guys.
I got a error when I tried to integrate Fabric and Firebase:

![image](https://user-images.githubusercontent.com/1860289/34944015-18cdf420-f9e5-11e7-9257-bfcd8474e7e0.png)

`cordova-fabric-plugin 1.1.10 "cordova-fabric-plugin"`

Do you know what should I do to resolve that?

Thanks.

**Comment by bmwertman** [comment]
I got past the Crashlytics SDK point but when I get to the last check box it says no events detected in firebase. Were you able to solve this?

**Comment by 814k31** [comment]
I manually updated the plugin inside fabrics build.gradle `platforms/android/cordova-fabric-plugin/<project>-build-extras.gradle`
 And changed the lines:
```
dependencies {
  compile('com.crashlytics.sdk.android:crashlytics:2.6.8@aar') {
    transitive = true;
  }
}
```
to 
```
dependencies {
  compile('com.crashlytics.sdk.android:crashlytics:2.8.0@aar') {
    transitive = true;
  }
}
```

Of course this could cause errors elsewhere as the plugin developers will have to upgrade crashlytics in the plugin and test if it breaks anything

**Comment by 814k31** [comment]
@bmwertman I would say you may have issues with setting up firebase analytics itself
Check the log cat for the program to see if you have errors along the line of `Missing google_app_id. Firebase Analytics disabled` (This message will not appear in chrome inspector)
https://github.com/chemerisuk/cordova-plugin-firebase-analytics/issues/13

Otherwise good luck

**Comment by 814k31** [comment]
#117 is also relevant here
